### ISSUE TITLE
Output Viewport Does Not Match out_bbox

### ISSUE THREAD

**Issue by jbeuckm** [DanielJDufour/geowarp#4]
I am trying to warp [this GeoTiff](https://nassgeodata.gmu.edu/webservice/nass_data_cache/CDL_2008_clip_20220323194315_1211782049.tif) into EPSG:4326 to generate a tile for Mapbox.

![input](https://user-images.githubusercontent.com/137068/159816714-e6ab27c2-7170-4d58-b8bd-29f3ca47a054.png)

Parsing with `georaster` seems to give the expected result:
```
  height: 570,
  width: 501,
  pixelHeight: 56,
  pixelWidth: 56,
  xmin: 450278,
  xmax: 478334,
  ymax: 1891090,
  ymin: 1859170,
```

When I `geowarp()` with these params, I get a correctly sized result that looks like the projection of a small piece of the top left corner of the source raster:
```
  const georaster = await parseGeoraster('https://nassgeodata.gmu.edu/webservice/nass_data_cache/CDL_2008_clip_20220323194315_1211782049.tif')

  const options = {
    left: 0,
    top: 0,
    right: georaster.width,
    bottom: georaster.height,
    width: georaster.width,
    height: georaster.height,
  }

  const values = await georaster.getValues(options)

  const result = geowarp({
    debug_level: 2,
    forward: albersConicalEqualArea.inverse,
    inverse: albersConicalEqualArea.forward,
    in_data: values[0],
    in_bbox: [xmin, ymin, xmax, ymax],
    in_layout: '[row][column,band]',
    in_pixel_depth: 1,
    in_srs: ALBERS_CONICAL_EQUAL_AREA,
    in_width: georaster.pixelWidth,
    in_height: georaster.pixelHeight,
    out_bbox: [west, south, east, north],
    out_layout: '[row][column,band]',
    out_srs: 4326,
    out_height: 256,
    out_width: 256,
    method: 'near',
    round: false,
    theoretical_min: 0,
    theoretical_max: 255,
  })

```

The requested output bbox is a direct projection of the bbox in the source tiff:
```
[geowarp] out_xmin: -90.703125
[geowarp] out_ymin: 39.6395375643667
[geowarp] out_xmax: -90.3515625
[geowarp] out_ymax: 39.909736234537185
```

The result is the correct size, but does not appear to match the requested output bbox:
![temp](https://user-images.githubusercontent.com/137068/159815517-2bf034f4-3779-41bc-884c-94ad19b53754.png)

The result looks to be a projected version of a small, top left piece of the input tiff:
<img width="302" alt="Screen Shot 2022-03-23 at 7 04 12 PM" src="https://user-images.githubusercontent.com/137068/159816266-fb0e9989-8f83-4c81-bdeb-54939d6d28ed.png">

**Comment by DanielJDufour** [comment]
Hi. Thanks for submitting this issue and a great write-up!  I'll look into this as soon as I can (but that might not be till the weekend).

Did you happen to see if you ran into this problem with older versions of geowarp?

Thank you again for reporting this issue! :-)

**Comment by jbeuckm** [comment]
I think i found the issue. I'm not sure what `georaster.pixelWidth/georaster.pixelHeight` are, but they are too small to use for the input dimensions. This works as expected if I use `georaster.width/georaster.height`.

Note: I added the dependencies to my project and copied in geowarp.js because my project did not accept the [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) when imported from this module.

**Comment by DanielJDufour** [comment]
@jbeuckm , good catch!  You have it correct.
